In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"D:\after2017 (1).csv")

In [3]:
df.head()

,Unnamed: 0,state,medical_code,medical_description,april,may,june,july,august,september,october,november,december,january,february,march,total,year
0,0,A & N Islands,1.1,Total number of pregnant women registered for ANC,432.0,406.0,400.0,498.0,436.0,445.0,429.0,458.0,371.0,425.0,488.0,422.0,5210.0,2017-2018
1,1,A & N Islands,1.1.1,"Out of the total ANC registered, number regist...",351.0,300.0,291.0,381.0,326.0,343.0,331.0,344.0,286.0,315.0,329.0,316.0,3913.0,2017-2018
2,2,A & N Islands,1.2.1,Number of PW given TT1,347.0,317.0,293.0,373.0,332.0,338.0,378.0,352.0,297.0,326.0,369.0,318.0,4040.0,2017-2018
3,3,A & N Islands,1.2.2,Number of PW given TT2,275.0,300.0,272.0,260.0,323.0,288.0,274.0,307.0,291.0,291.0,283.0,305.0,3469.0,2017-2018
4,4,A & N Islands,1.2.3,Number of PW given TT Booster,81.0,63.0,72.0,88.0,68.0,71.0,80.0,82.0,60.0,71.0,74.0,60.0,870.0,2017-2018

In [4]:
# Pivot the table
pivoted_df = df.pivot(index=['state', 'year'], columns='medical_description', values='total')

In [5]:
# Reset index to make 'state' and 'year' regular columns
pivoted_df = pivoted_df.reset_index()

In [6]:
pivoted_df.head()

medical_description,state,year,Abortion (spontaneous),Allopathic- Outpatient attendance,Ayush - Outpatient attendance,Blood Units Issued on replacement (Family Donors to be considered as replacement donations),Boys (6th -12th class) provided 4 IFA tablets in schools,Boys (6th -12th class) provided albendazole in schools,Boys registered in AFHC,"C-sections, performed at night (8 PM- 8 AM)",...,Total C -Section deliveries performed,Total Facility Based Maternal Death Reviews (FBMDR) done,Total Maternal Deaths Reviewed (MDR) by CMO,Total Maternal Deaths Reviewed (MDR) by DM,Total number of blood units issued in year,Total number of pregnant women registered for ANC,Widal tests - Number Positive,Widal tests - Number Tested,Women receiving 1st post partum checkup between 48 hours and 14 days,Women receiving 1st post partum checkup within 48 hours of home delivery
0,A & N Islands,2017-2018,143.0,1744255.0,122773.0,0.0,NaN,NaN,10358.0,114.0,...,922.0,0.0,NaN,NaN,0.0,5210.0,1120078.0,12585.0,3203.0,1931.0
1,A & N Islands,2018-2019,121.0,1781003.0,114010.0,56.0,NaN,NaN,1119.0,130.0,...,1030.0,0.0,NaN,NaN,1651.0,4972.0,886195.0,10840.0,3379.0,675.0
2,A & N Islands,2019-2020,143.0,2348015.0,128862.0,52.0,370499.0,41038.0,1607.0,121.0,...,1031.0,0.0,0.0,0.0,4552.0,4784.0,983.0,10882.0,2772.0,393.0
3,Andhra Pradesh,2017-2018,9042.0,69703125.0,2805619.0,19578.0,6530721.0,1346424.0,89941.0,30036.0,...,237642.0,148.0,315.0,300.0,123099.0,830965.0,65938.0,496594.0,549158.0,111465.0
4,Andhra Pradesh,2018-2019,8958.0,76458027.0,2657570.0,40408.0,20762904.0,3804985.0,92620.0,40053.0,...,270676.0,160.0,392.0,312.0,329666.0,858326.0,62893.0,522994.0,595971.0,9956.0

In [7]:
pivoted_df.shape

(114, 328)

In [8]:
pivoted_df["state"].nunique()

38

In [9]:
# Get unique medical descriptions for each state
unique_descriptions = df.groupby('state')['medical_description'].nunique()

In [10]:
unique_descriptions

state
A & N Islands           326
Andhra Pradesh          326
Arunachal Pradesh       326
Assam                   326
Bihar                   326
Chandigarh              326
Chhattisgarh            326
Dadra & Nagar Haveli    326
Daman & Diu             326
Delhi                   326
Goa                     326
Gujarat                 326
Haryana                 326
Himachal Pradesh        326
Jammu & Kashmir         326
Jharkhand               326
Karnataka               326
Kerala                  326
Lakshadweep             326
M/O Defence             326
M/O Railways            326
Madhya Pradesh          326
Maharashtra             326
Manipur                 326
Meghalaya               326
Mizoram                 326
Nagaland                326
Odisha                  326
Puducherry              326
Punjab                  326
Rajasthan               326
Sikkim                  326
Tamil Nadu              326
Telangana               326
Tripura                 326
Uttar Pradesh           326
Uttarakhand             326
West Bengal             326
Name: medical_description, dtype: int64

In [11]:
pivoted_df["year"].iloc[1]

'2018-2019'

In [12]:
pivoted_df[pivoted_df["year"]=='2017-2018']

medical_description,state,year,Abortion (spontaneous),Allopathic- Outpatient attendance,Ayush - Outpatient attendance,Blood Units Issued on replacement (Family Donors to be considered as replacement donations),Boys (6th -12th class) provided 4 IFA tablets in schools,Boys (6th -12th class) provided albendazole in schools,Boys registered in AFHC,"C-sections, performed at night (8 PM- 8 AM)",...,Total C -Section deliveries performed,Total Facility Based Maternal Death Reviews (FBMDR) done,Total Maternal Deaths Reviewed (MDR) by CMO,Total Maternal Deaths Reviewed (MDR) by DM,Total number of blood units issued in year,Total number of pregnant women registered for ANC,Widal tests - Number Positive,Widal tests - Number Tested,Women receiving 1st post partum checkup between 48 hours and 14 days,Women receiving 1st post partum checkup within 48 hours of home delivery
0,A & N Islands,2017-2018,143.0,1744255.0,122773.0,0.0,NaN,NaN,10358.0,114.0,...,922.0,0.0,NaN,NaN,0.0,5210.0,1120078.0,12585.0,3203.0,1931.0
3,Andhra Pradesh,2017-2018,9042.0,69703125.0,2805619.0,19578.0,6530721.0,1346424.0,89941.0,30036.0,...,237642.0,148.0,315.0,300.0,123099.0,830965.0,65938.0,496594.0,549158.0,111465.0
6,Arunachal Pradesh,2017-2018,523.0,1264419.0,91349.0,329.0,19004.0,173.0,3237.0,289.0,...,3413.0,1.0,4.0,4.0,1246.0,32373.0,6084.0,34381.0,8823.0,8652.0
9,Assam,2017-2018,23768.0,31827450.0,2052206.0,45630.0,4184568.0,890665.0,4322.0,30576.0,...,113087.0,238.0,380.0,129.0,91078.0,689620.0,12237.0,109094.0,458371.0,128616.0
12,Bihar,2017-2018,4697.0,64078509.0,11748587.0,27341.0,45.0,137014.0,21593.0,5536.0,...,40674.0,171.0,170.0,97.0,53572.0,3187592.0,16681.0,68993.0,856432.0,548603.0
15,Chandigarh,2017-2018,2222.0,6624248.0,255986.0,10104.0,366386.0,114383.0,4500.0,4934.0,...,9413.0,1.0,NaN,NaN,156556.0,41894.0,4391.0,36294.0,1596.0,3418.0
18,Chhattisgarh,2017-2018,22513.0,19905006.0,997407.0,22935.0,1754992.0,427770.0,16631.0,20136.0,...,75286.0,49.0,182.0,128.0,58582.0,634235.0,113978.0,473491.0,345063.0,95969.0
21,Dadra & Nagar Haveli,2017-2018,600.0,1816962.0,25595.0,3041.0,33047.0,0.0,3804.0,904.0,...,2587.0,2.0,4.0,0.0,11075.0,8362.0,771.0,24562.0,4146.0,62.0
24,Daman & Diu,2017-2018,119.0,800549.0,63696.0,76.0,142483.0,13620.0,2156.0,98.0,...,945.0,0.0,0.0,0.0,579.0,7888.0,1241.0,10784.0,1448.0,4.0
27,Delhi,2017-2018,23443.0,67123188.0,3855595.0,61125.0,0.0,0.0,97652.0,19172.0,...,75937.0,284.0,184.0,6.0,292768.0,982022.0,45109.0,319278.0,171179.0,35721.0
30,Goa,2017-2018,604.0,1979740.0,99997.0,236.0,635981.0,130845.0,25979.0,919.0,...,7722.0,2.0,0.0,15.0,2914.0,24503.0,546.0,3497.0,14390.0,2.0
33,Gujarat,2017-2018,28517.0,67428952.0,3398857.0,12056.0,11977369.0,2991094.0,127900.0,22613.0,...,187314.0,187.0,1025.0,512.0,306514.0,1420598.0,25392.0,395629.0,901334.0,145713.0
36,Haryana,2017-2018,18146.0,27376115.0,2326863.0,5714.0,1117834.0,1339911.0,73013.0,2841.0,...,83688.0,2.0,155.0,0.0,120007.0,567940.0,20496.0,293837.0,373927.0,26741.0
39,Himachal Pradesh,2017-2018,5697.0,13800985.0,2574.0,1742.0,1070117.0,235432.0,10473.0,1565.0,...,17131.0,2.0,3.0,0.0,18042.0,118864.0,16474.0,110247.0,83971.0,37068.0
42,Jammu & Kashmir,2017-2018,11143.0,26130851.0,1531121.0,7614.0,261888.0,204502.0,20611.0,12139.0,...,70713.0,5.0,53.0,8.0,26076.0,399307.0,14952.0,141579.0,145200.0,35393.0
45,Jharkhand,2017-2018,18476.0,14553467.0,368842.0,26739.0,3861937.0,1045301.0,38346.0,4136.0,...,53764.0,125.0,287.0,139.0,45460.0,959918.0,17411.0,90001.0,354757.0,172196.0
48,Karnataka,2017-2018,23821.0,90495697.0,3891804.0,42053.0,10988143.0,1906197.0,202573.0,49891.0,...,256283.0,167.0,173.0,116.0,423525.0,1097374.0,135450.0,907422.0,873614.0,105634.0
51,Kerala,2017-2018,12175.0,120423894.0,206845.0,10077.0,3677860.0,1441608.0,21574.0,11970.0,...,184992.0,23.0,2.0,0.0,36283.0,565673.0,6460.0,203766.0,737598.0,76716.0
54,Lakshadweep,2017-2018,107.0,396439.0,67060.0,0.0,0.0,3535.0,0.0,43.0,...,323.0,0.0,0.0,0.0,0.0,1292.0,57.0,496.0,520.0,92.0
57,M/O Defence,2017-2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,M/O Railways,2017-2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Madhya Pradesh,2017-2018,35996.0,49548275.0,2651203.0,114936.0,9989541.0,2231396.0,72657.0,20310.0,...,130143.0,267.0,447.0,198.0,212818.0,1832836.0,48713.0,605256.0,318034.0,145820.0
66,Maharashtra,2017-2018,60109.0,90946872.0,5871519.0,5770.0,27402767.0,2915174.0,411160.0,61493.0,...,350799.0,748.0,607.0,178.0,301762.0,2180670.0,182823.0,1051249.0,1137186.0,12519.0
69,Manipur,2017-2018,2391.0,1294110.0,113676.0,950.0,61285.0,25542.0,8452.0,785.0,...,7212.0,1.0,0.0,0.0,2118.0,55807.0,2611.0,11585.0,19816.0,4916.0
72,Meghalaya,2017-2018,4173.0,4029859.0,325210.0,2722.0,520469.0,96625.0,12057.0,1284.0,...,6592.0,20.0,91.0,13.0,3506.0,131034.0,16036.0,68544.0,42113.0,26518.0
75,Mizoram,2017-2018,1131.0,1332810.0,42553.0,4155.0,278035.0,47662.0,5379.0,453.0,...,3120.0,1.0,0.0,0.0,12615.0,21582.0,3360.0,24561.0,14007.0,3908.0
78,Nagaland,2017-2018,509.0,1068668.0,34689.0,2360.0,46606.0,42833.0,7457.0,343.0,...,2854.0,17.0,20.0,2.0,10589.0,37217.0,5358.0,28149.0,9402.0,4642.0
81,Odisha,2017-2018,39106.0,45375178.0,6325497.0,61382.0,4773624.0,1609429.0,18885.0,15082.0,...,94348.0,144.0,703.0,476.0,229067.0,739001.0,38388.0,199613.0,536555.0,31391.0
84,Puducherry,2017-2018,1136.0,8485075.0,903703.0,219.0,247172.0,113436.0,46912.0,4129.0,...,14082.0,9.0,NaN,NaN,1762.0,88665.0,951.0,18029.0,27169.0,18145.0
87,Punjab,2017-2018,17659.0,22349964.0,4039046.0,8605.0,6732003.0,1384616.0,21047.0,15223.0,...,128490.0,234.0,632.0,447.0,116222.0,464094.0,40348.0,338303.0,339470.0,51592.0
90,Rajasthan,2017-2018,60825.0,110256818.0,4077425.0,75440.0,3143966.0,592637.0,274387.0,11144.0,...,147494.0,40.0,336.0,252.0,164266.0,1884090.0,62444.0,1408417.0,309271.0,60626.0
93,Sikkim,2017-2018,372.0,1118439.0,21153.0,131.0,293629.0,22965.0,10486.0,23.0,...,2163.0,0.0,3.0,3.0,1218.0,8925.0,83.0,1505.0,6558.0,2081.0
96,Tamil Nadu,2017-2018,38960.0,232065172.0,29068032.0,227.0,22266784.0,6014320.0,156889.0,62093.0,...,412180.0,165.0,503.0,422.0,88587.0,1022933.0,78604.0,972441.0,14321.0,2782.0
99,Telangana,2017-2018,4877.0,36475505.0,2203977.0,14880.0,1683602.0,404144.0,27024.0,24227.0,...,267781.0,190.0,47.0,23.0,43590.0,1179409.0,117337.0,431895.0,406308.0,92759.0
102,Tripura,2017-2018,1676.0,4089652.0,352647.0,7583.0,628492.0,116453.0,3810.0,1036.0,...,11173.0,0.0,15.0,10.0,23763.0,75540.0,3330.0,23886.0,36961.0,4662.0
105,Uttar Pradesh,2017-2018,31684.0,125680209.0,16681637.0,162773.0,2475841.0,455171.0,517767.0,27873.0,...,153015.0,362.0,836.0,470.0,375547.0,5818739.0,327592.0,1675008.0,1260263.0,1408306.0
108,Uttarakhand,2017-2018,3530.0,7724120.0,814329.0,2897.0,224543.0,264631.0,32050.0,1576.0,...,16942.0,24.0,95.0,40.0,11286.0,229256.0,19066.0,92663.0,75771.0,56559.0
111,West Bengal,2017-2018,77820.0,123561557.0,3221875.0,54518.0,4512035.0,122359.0,405883.0,74040.0,...,418363.0,483.0,512.0,103.0,641029.0,1656977.0,28558.0,207862.0,1162920.0,366903.0